### ISSUE TITLE
Interprocess handle sharing.

### ISSUE THREAD

**Issue by vvchyron** [leetvr/lazy_vulkan#2]
Hello,
first of all thank you very much for provided example. This is more question then an issue, but I do not know where to better place it.

I am not much familiar with Rust, so maybe I am just overlooking something,
but I was trying to do something simmilar in C++, where there was a server and
client process. Server used to create external memory and pass the `HANDLE` to it obtained
by `vkGetMemoryWin32HandleKHR` to the client via shared memory,
Client imported the memory to OpenGL api, by calling `glImportMemoryWin32HandleEXT` using that `HANDLE`
(which I proved working already before within one process).

This import part is something I do not understand in your remote_host.rs and remote_client.rs
examples, as they are different processes, so they do not share the same memory mapping,
so how it is possible that the `HANDLE` from host process is valid in the client process too?
I would expect you need to call something like `DuplicateHandle` (in windows) to export the handle to the client
to be able to import from external memory, but it seems to me, that you just IPC the original
`HANDLE` value from host to client. Is that so?

Or there is some framework magic doing this `HANDLE` export, or both processes are set to the same memory mapping?

Thank you for reading until here and your time,
best regards,
VojtaV

**Comment by kanerogers** [comment]
Hi, there!

Thanks so much for your detailed and thoughtfully worded question.

For context, I'm absolutely not a Windows Developer; I know very little about the process model on Windows, so my understanding may be flawed in some way.

However, my understanding from reading the spec of the extension used to obtain a handle to image memory on Windows, [VK_KHR_external_memory_win32](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_external_memory_win32.html) is that there are two kinds of handle:

- `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT`
- VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT

Where the KMT variant is a "global share handle" as opposed to an "NT handle". My understanding is that the KMT variant is bad simpler, as it does not require specifying fine grained permissions on the handle, however it is, for those same reasons, less secure. I also believe that using the KMT variant means no single process owns the memory, which means it's more complicated to safely clean up objects that might be using it.

I hope that makes more sense! The documentation for this extension is, like most Vulkan extensions, a little difficult to read as it is spread throughout the various members of the extension, but I recommend reading through both the Windows specific spec and the parent spec https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_external_memory.html. 

Let me know if you have any further questions!

**Comment by vvchyron** [comment]
Thank you for the response.

I made it work in the end, using `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT` in combination with `DuplicateHandel` on the client side as `VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT` was not working for me, resulting in error when trying to import the memory to OpenGL through `glImportMemoryWin32HandleEXT`, but maybe I just messed up something.

My original idea was the same as you described, but I did not have any backing knowledge to consider the KMT to be globaly shared except the hint in the extension docs:

> VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_ specifies a global share handle that has only limited valid usage...

(actualy it should be just some old handle version used for win7 and older, NT handles are win8+ on the other hand), and still I was not able to find what this _globaly shared_ actaully really means IPC wise.

Also I think that in case of unix based systems, you can share the FDs without any issue between processes, so that might be the reason why it works out of the box (but I might be wrong, as it is nearly a decade when I was working with unix-based stuff).

Although thank you very much, I appreciate your help a lot, have a nice day.
